create extension if not exists pgcrypto;

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  creator_name text not null check (char_length(creator_name) between 1 and 30),
  item_count integer not null check (item_count between 1 and 200),
  submitted_at timestamptz not null default now()
);

create table if not exists public.selection_items (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.submissions(id) on delete cascade,
  sku text not null,
  product_name text not null,
  category text not null,
  style text,
  plan_level text,
  price numeric,
  image_url text,
  is_featured boolean not null default false,
  intent text not null default '直播挂车',
  remark text not null default '',
  created_at timestamptz not null default now()
);

alter table public.selection_items
  add column if not exists style text,
  add column if not exists plan_level text,
  add column if not exists price numeric,
  add column if not exists image_url text,
  add column if not exists is_featured boolean not null default false,
  add column if not exists intent text not null default '鐩存挱鎸傝溅',
  add column if not exists remark text not null default '',
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.product_overrides (
  sku text primary key,
  price numeric,
  image_url text,
  plan_level text,
  style text,
  updated_by text,
  updated_at timestamptz not null default now()
);

alter table public.product_overrides
  add column if not exists price numeric,
  add column if not exists image_url text,
  add column if not exists plan_level text,
  add column if not exists style text,
  add column if not exists updated_by text,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists selection_items_submission_id_idx
  on public.selection_items(submission_id);
create index if not exists selection_items_sku_idx
  on public.selection_items(sku);
create index if not exists submissions_submitted_at_idx
  on public.submissions(submitted_at desc);
create index if not exists product_overrides_updated_at_idx
  on public.product_overrides(updated_at desc);

alter table public.submissions enable row level security;
alter table public.selection_items enable row level security;
alter table public.product_overrides enable row level security;

drop policy if exists "authenticated can read submissions" on public.submissions;
create policy "authenticated can read submissions"
  on public.submissions for select to authenticated
  using ((auth.jwt() ->> 'email') = 'yanjianxi02@gmail.com');

drop policy if exists "authenticated can read selection items" on public.selection_items;
create policy "authenticated can read selection items"
  on public.selection_items for select to authenticated
  using ((auth.jwt() ->> 'email') = 'yanjianxi02@gmail.com');

drop policy if exists "anyone can read product overrides" on public.product_overrides;
create policy "anyone can read product overrides"
  on public.product_overrides for select to anon, authenticated
  using (true);

drop policy if exists "admin can write product overrides" on public.product_overrides;
create policy "admin can write product overrides"
  on public.product_overrides for all to authenticated
  using ((auth.jwt() ->> 'email') = 'yanjianxi02@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'yanjianxi02@gmail.com');

create or replace function public.submit_selection(
  p_creator_name text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_submission_id uuid;
  v_item_count integer;
begin
  p_creator_name := btrim(p_creator_name);
  v_item_count := jsonb_array_length(p_items);

  if char_length(p_creator_name) < 1 or char_length(p_creator_name) > 30 then
    raise exception 'invalid creator name';
  end if;
  if v_item_count < 1 or v_item_count > 200 then
    raise exception 'invalid item count';
  end if;

  insert into public.submissions (creator_name, item_count)
  values (p_creator_name, v_item_count)
  returning id into v_submission_id;

  insert into public.selection_items (
    submission_id, sku, product_name, category, style, plan_level,
    price, image_url, is_featured, intent, remark
  )
  select
    v_submission_id,
    left(coalesce(item->>'sku', ''), 50),
    left(coalesce(item->>'product_name', ''), 100),
    left(coalesce(item->>'category', ''), 50),
    left(coalesce(item->>'style', ''), 100),
    left(coalesce(item->>'plan_level', ''), 10),
    case when item->>'price' ~ '^[0-9]+(\.[0-9]+)?$'
      then (item->>'price')::numeric else null end,
    left(coalesce(item->>'image_url', ''), 1000),
    coalesce((item->>'is_featured')::boolean, false),
    left(coalesce(item->>'intent', '直播挂车'), 50),
    left(coalesce(item->>'remark', ''), 500)
  from jsonb_array_elements(p_items) as item;

  return v_submission_id;
end;
$$;

revoke all on function public.submit_selection(text, jsonb) from public;
grant execute on function public.submit_selection(text, jsonb) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'submissions'
  ) then
    alter publication supabase_realtime add table public.submissions;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'selection_items'
  ) then
    alter publication supabase_realtime add table public.selection_items;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'product_overrides'
  ) then
    alter publication supabase_realtime add table public.product_overrides;
  end if;
end $$;
